[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  GENERATE_SOURCEMAP = "false"
  CI = "false"

# Exclude native files and directories
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Ignore patterns for native files
[build.ignore]
  patterns = [
    "**/*.h",
    "**/*.cpp", 
    "**/*.java",
    "**/*.kt",
    "**/*.swift",
    "**/android/**",
    "**/ios/**",
    "**/node_modules/**/*.h",
    "**/node_modules/**/*.cpp",
    "**/node_modules/**/*.java",
    "**/node_modules/**/*.kt",
    "**/node_modules/**/*.swift"
  ]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.mp4"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webm"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
